# Generated by Django 3.2.4 on 2021-10-12 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_component', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhistory',
            name='model_utilized',
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='transaction_charge',
            field=models.IntegerField(default=0),
        ),
    ]
