# Generated by Django 3.2.4 on 2021-10-12 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_component', '0002_auto_20211012_0329'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SemanticModel',
        ),
    ]
