# Generated by Django 3.2.4 on 2021-10-12 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_component', '0003_delete_semanticmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userhistory',
            old_name='quert_count',
            new_name='query_count',
        ),
    ]
