# Generated by Django 3.2.4 on 2021-11-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_component', '0005_userdetail_saved_query_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhistory',
            name='credit_added',
            field=models.BooleanField(default=False),
        ),
    ]
