# Generated by Django 3.2.4 on 2021-11-07 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_component', '0006_userhistory_credit_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorySentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(default='Sentence Not Available', max_length=500)),
                ('history_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_component.userhistory')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
